---
runtime: shiny
output: html_document
---

### Here are two Shiny widgets

```{r}
library(shiny)
library(plotly)
library(Matrix)
library(ggplot2)
library(monocle)


#--------------------------------------------------#
#--------------Creating cellDataSet----------------#
#--------------------------------------------------#
#import exprs

exprs <- read.delim(file = "EA_Ngn3_160701.csv", header = TRUE)
#exprs <- read.csv (file = "allgen.csv", header = TRUE)
#algen <- data.frame(file= "allgen.csv", row.names=NUll, colnames=names("x"))
samp <- sapply(colnames(exprs),function(x) strsplit(x,'\\.')[[1]][2])

#meta data = plate code info 
pheno <- c('Ngn3','horm','Ngn3','duct','horm','Ngn3-cre','Ngn3-cre')
names(pheno) <- c('EA01','EA02','EA03','EA04','EA05','EA06','EA07')
pheno <- data.frame(attr = sapply(samp, function(x) pheno[which(x == names(pheno))]))
phenof <-as.data.frame(t(pheno))
rownames(pheno) <- colnames(exprs)
#write.csv (phenof, "~/Downloads/Test_shiny/App2/phenof.csv")

#make rows in pheno same as columns in counts
exprs <- exprs[,rownames(pheno)]
all(rownames(pheno) == colnames(exprs))

#create featureData
feature <- data.frame(row.names(exprs), feat = "protein_coding")
colnames(feature)[1] <- "gene_short_name"
row.names(feature) <- row.names(exprs)

#create CellDataSet
pd <- AnnotatedDataFrame(data = pheno)
fd <- AnnotatedDataFrame(data = feature)
cds <- newCellDataSet(as.matrix(exprs), phenoData = pd, featureData = fd, expressionFamily = negbinomial.size(), lowerDetectionLimit=0.1) 

#pre-calculate information about the data
cds <- estimateSizeFactors(cds)
cds <- estimateDispersions(cds)  # removed 113 outliers
my_cds<- detectGenes(cds, min_expr= 0.1)

#--------------------------------------------------#
#--------Clustering Cells Without Marker Genes-----#
#--------------------------------------------------#

disp_table <- dispersionTable(my_cds)

unsup_clustering_genes <- subset(disp_table, mean_expression >= 1)
my_cds <- setOrderingFilter(my_cds, unsup_clustering_genes$gene_id)

my_cds <- reduceDimension(my_cds, max_components = 2, num_dim = 6, 
                          reduction_method = 'tSNE', verbose = TRUE,
                          label_groups_by_cluster = TRUE) 
my_cds <- clusterCells(my_cds, num_clusters = 7) 
```

```{r echo = FALSE}
 sidebarPanel(
    selectInput('genes',label='Choose Markers (Top 10 markers)', choices=c(choose=" ", "Neurog3", "Neurod2", "Chga", "Cpa1", "Ins1"), selected = " "))
                 
    mainPanel(
    #selectInput('my_dropdown','Choose Markers',colnames(mtcars)),
                #row (2, align="right", 
                plotOutput("plot_cell_clusters1"),
                plotOutput("plot_cell_clusters2"))


```

### ...that build a histogram.

```{r echo = FALSE}

renderPlot (
      plot_cell_clusters (my_cds, colors_by="Cluster"))
```

```{r plot}
  
renderPlot(
      
      if (input$genes== "Neurog3")
      {plot_cell_clusters (my_cds, markers="Neurog3")}
)
```

```{r plot}
renderPlot(
      if (input$genes== "Chga")
      {plot_cell_clusters (my_cds, markers="Chga")}
)
```

```{r plot}
renderPlot(     
      if (input$genes== "Cpa1")
      {plot_cell_clusters (my_cds, markers="Cpa1")}
)
```

```{r plot}
renderPlot(
     if (input$genes== "Ins1")
     {plot_cell_clusters (my_cds, markers="Ins1")}
)
```   

